// Generated by CoffeeScript 1.6.3
(function() {
  var h;

  window.heightmap = function() {
    var me;
    me = this;
    this.dom = document.querySelector('.main');
    this.data = [];
    this.size = {
      x: 15,
      y: 15
    };
    this.init = function() {
      var i, j, _i, _ref, _results;
      me.data = [];
      _results = [];
      for (j = _i = 0, _ref = me.size.y; 0 <= _ref ? _i <= _ref : _i >= _ref; j = 0 <= _ref ? ++_i : --_i) {
        me.data.push([]);
        _results.push((function() {
          var _j, _ref1, _results1;
          _results1 = [];
          for (i = _j = 0, _ref1 = me.size.x; 0 <= _ref1 ? _j <= _ref1 : _j >= _ref1; i = 0 <= _ref1 ? ++_j : --_j) {
            _results1.push(me.data[j].push(void 0));
          }
          return _results1;
        })());
      }
      return _results;
    };
    this.build = function(start) {
      var a, i, j, _i, _j, _k, _l, _ref, _ref1, _ref2, _ref3;
      me.init();
      me.data[0][0] = start;
      for (i = _i = 1, _ref = me.size.x; 1 <= _ref ? _i <= _ref : _i >= _ref; i = 1 <= _ref ? ++_i : --_i) {
        me.data[0][i] = me.data[0][i - 1] + Math.floor(Math.random() * 1.49 - 0.24);
      }
      for (j = _j = 1, _ref1 = me.size.y; 1 <= _ref1 ? _j <= _ref1 : _j >= _ref1; j = 1 <= _ref1 ? ++_j : --_j) {
        me.data[j][0] = me.data[j - 1][0] + Math.floor(Math.random() * 1.49 - 0.24);
      }
      for (j = _k = 1, _ref2 = me.size.y; 1 <= _ref2 ? _k <= _ref2 : _k >= _ref2; j = 1 <= _ref2 ? ++_k : --_k) {
        for (i = _l = 1, _ref3 = me.size.x; 1 <= _ref3 ? _l <= _ref3 : _l >= _ref3; i = 1 <= _ref3 ? ++_l : --_l) {
          if (Math.abs(me.data[j][i - 1] - me.data[j - 1][i]) === 2) {
            me.data[j][i] = me.data[j - 1][i - 1];
          } else if (me.data[j][i - 1] === me.data[j - 1][i]) {
            me.data[j][i] = me.data[j][i - 1] + Math.floor(Math.random() * 1.49 - 0.24);
          } else {
            a = Math.floor(Math.random() * 1.99);
            me.data[j][i] = me.data[j - a][i + a - 1];
          }
        }
      }
      return console.log('Built');
    };
    this.render = function() {
      var htm, i, j, _i, _j, _len, _len1, _ref;
      htm = '<table>';
      _ref = me.data;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        j = _ref[_i];
        htm += '<tr>';
        for (_j = 0, _len1 = j.length; _j < _len1; _j++) {
          i = j[_j];
          htm += '<td>' + i + '</td>';
        }
        htm += '</tr>';
      }
      htm += '</table>';
      return me.dom.innerHTML = htm;
    };
    return this;
  };

  h = new window.heightmap();

  h.build(50);

  h.render();

}).call(this);
